name: Upload Docs to R2
on:
  push:
    branches: [ main ]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: |
            curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
            unzip rclone-current-linux-amd64.zip
            cd rclone-*-linux-amd64
            sudo cp rclone /usr/bin/
            sudo chown root:root /usr/bin/rclone
            sudo chmod 755 /usr/bin/rclone
            sudo mkdir -p /usr/local/share/man/man1
            sudo cp rclone.1 /usr/local/share/man/man1/
            sudo mandb
            rclone config create r2 s3 provider=Cloudflare access_key_id=${{ secrets.R2_ACCESS_KEY_ID }} secret_access_key=${{ secrets.R2_SECRET_ACCESS_KEY }} region=auto endpoint=${{ secrets.ENDPOINT }} acl=private
