name: Upload Docs to R2
on:
  push:
    branches: [ main ]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: R2 Upload Action
        uses: willfurstenau/r2-dir-upload@v1
        with:
          accountid: ${{ secrets.R2_ACCOUNT_ID }}
          accesskeyid: ${{ secrets.R2_ACCESS_KEY_ID }}
          secretaccesskey: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.R2_BUCKET }}
          source: ${{ github.workspace }}/
          destination: /
